cargo-features = ["edition"]

[package]
name = "tipe2"
version = "0.1.0"
authors = ["Th√©o Degioanni <moxinilian@tutanota.com>"]
edition = "2018"

[dependencies]
nalgebra = "0.16"
ncollide3d = "0.17"
rand = "0.5"
rayon = "1.0"
serde = "1.0"
